# Random Forest Regression

## Importing the libraries

In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [32]:
dataset = pd.read_csv('Data10.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Random Forest Regression model on the whole dataset

In [34]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(random_state=0)

## Predicting the Test set results

In [35]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0.   0.  ]
 [0.15 0.  ]
 [0.02 0.  ]
 [0.   0.  ]
 [0.95 1.  ]
 [0.02 0.  ]
 [0.63 1.  ]
 [0.   0.  ]
 [0.07 0.  ]
 [0.69 1.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.69 1.  ]
 [0.01 0.  ]
 [0.   0.  ]
 [0.08 0.  ]
 [0.13 0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.01 0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.75 1.  ]
 [0.22 1.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.66 1.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.13 0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.27 0.  ]
 [0.76 1.  ]
 [0.13 0.  ]
 [0.   0.  ]
 [0.54 1.  ]
 [0.   0.  ]
 [0.01 0.  ]
 [0.01 0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.08 0.  ]
 [0.94 1.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]]


Predict

In [40]:
regressor.predict([[98.6789,6.1543,6.4, 442147565180.721000 ,14.25123]])

array([0.31])

In [41]:
regressor.predict([[98.6789,6.1543,6.3, 442147565180.721000 ,14.25123]])

array([0.34])

In [42]:
regressor.predict([[98.6789,6.1543,6.2, 442147565180.721000 ,14.25123]])

array([0.44])

In [43]:
regressor.predict([[98.6789,6.1543,6.1, 442147565180.721000 ,14.25123]])

array([0.9])

In [44]:
regressor.predict([[98.6789,6.1543,6, 442147565180.721000 ,14.25123]])

array([0.9])

In [46]:
regressor.predict([[101,150,7, 25000000000000 ,105]])

array([0.21])

## Evaluating the Model Performance

In [45]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8098344444444445